/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtencionesRouteImport } from './routes/atenciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TendenciasHistoricasRouteImport } from './routes/tendencias-historicas'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsReportNameRouteImport } from './routes/reports/$reportName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtencionesRoute = AtencionesRouteImport.update({
  id: '/atenciones',
  path: '/atenciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasHistoricasRoute = TendenciasHistoricasRouteImport.update({
  id: '/tendencias-historicas',
  path: '/tendencias-historicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportNameRoute = ReportsReportNameRouteImport.update({
  id: '/reports/$reportName',
  path: '/reports/$reportName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atenciones': typeof AtencionesRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/tendencias-historicas': typeof TendenciasHistoricasRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atenciones': typeof AtencionesRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/tendencias-historicas': typeof TendenciasHistoricasRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atenciones': typeof AtencionesRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/tendencias-historicas': typeof TendenciasHistoricasRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atenciones'
    | '/login'
    | '/status'
    | '/tendencias-historicas'
    | '/reports/$reportName'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atenciones'
    | '/login'
    | '/status'
    | '/tendencias-historicas'
    | '/reports/$reportName'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/atenciones'
    | '/login'
    | '/status'
    | '/tendencias-historicas'
    | '/reports/$reportName'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtencionesRoute: typeof AtencionesRoute
  LoginRoute: typeof LoginRoute
  StatusRoute: typeof StatusRoute
  TendenciasHistoricasRoute: typeof TendenciasHistoricasRoute
  ReportsReportNameRoute: typeof ReportsReportNameRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atenciones': {
      id: '/atenciones'
      path: '/atenciones'
      fullPath: '/atenciones'
      preLoaderRoute: typeof AtencionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias-historicas': {
      id: '/tendencias-historicas'
      path: '/tendencias-historicas'
      fullPath: '/tendencias-historicas'
      preLoaderRoute: typeof TendenciasHistoricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportName': {
      id: '/reports/$reportName'
      path: '/reports/$reportName'
      fullPath: '/reports/$reportName'
      preLoaderRoute: typeof ReportsReportNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtencionesRoute: AtencionesRoute,
  LoginRoute: LoginRoute,
  StatusRoute: StatusRoute,
  TendenciasHistoricasRoute: TendenciasHistoricasRoute,
  ReportsReportNameRoute: ReportsReportNameRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
